### ISSUE TITLE
pcre2

### ISSUE THREAD

**Issue by esaaprillia** [nightlark/swig-pypi#152]
@nightlark 

can python-swig use existing pcre2? i have built pcre2

```
*** scikit-build-core 0.10.7 using CMake 3.30.5 (wheel)
*** Configuring CMake...
loading initial cache file /home/tmp/tmpl60pizbb/build/CMakeInit.txt
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/staging_dir/host/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found BISON: /home/staging_dir/host/bin/bison (found suitable version "3.8.2", minimum required is "3.5")
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/tmp/tmpl60pizbb/build
*** Building project with Ninja...
[1/24] Creating directories for 'PCRE2'
[2/24] Creating directories for 'BISON-bin'
[3/24] No download step for 'BISON-bin'
[4/24] No update step for 'BISON-bin'
[5/24] No patch step for 'BISON-bin'
[6/24] No configure step for 'BISON-bin'
[7/24] No build step for 'BISON-bin'
[8/24] No install step for 'BISON-bin'
[9/24] Completed 'BISON-bin'
[10/24] Performing download step (download, verify and extract) for 'PCRE2'
FAILED: PCRE2-prefix/src/PCRE2-stamp/PCRE2-download /home/tmp/tmpl60pizbb/build/PCRE2-prefix/src/PCRE2-stamp/PCRE2-download 
cd /home/tmp/tmpl60pizbb/build && /home/staging_dir/host/bin/cmake -DCMAKE_MESSAGE_LOG_LEVEL=VERBOSE -P /home/tmp/tmpl60pizbb/build/PCRE2-prefix/src/PCRE2-stamp/download-PCRE2.cmake && /home/staging_dir/host/bin/cmake -DCMAKE_MESSAGE_LOG_LEVEL=VERBOSE -P /home/tmp/tmpl60pizbb/build/PCRE2-prefix/src/PCRE2-stamp/verify-PCRE2.cmake && /home/staging_dir/host/bin/cmake -DCMAKE_MESSAGE_LOG_LEVEL=VERBOSE -P /home/tmp/tmpl60pizbb/build/PCRE2-prefix/src/PCRE2-stamp/extract-PCRE2.cmake && /home/staging_dir/host/bin/cmake -E touch /home/tmp/tmpl60pizbb/build/PCRE2-prefix/src/PCRE2-stamp/PCRE2-download
-- Downloading...
```

**Comment by nightlark** [comment]
The source distribution probably isn't set up in a way that would make so it can use an existing pcre2 at the moment.

I think you'd have to modify the CMakeLists.txt file for swig-pypi to recognize when some form of flag/environment variable that when set disables the PCRE2 download/build, and instead calls find_package to locate the pcre2 library on the system to get the PCRE2_LIBRARY and PCRE2_INCLUDE_DIR paths to use.

**Comment by esaaprillia** [comment]
> The source distribution probably isn't set up in a way that would make so it can use an existing pcre2 at the moment.
> 
> I think you'd have to modify the CMakeLists.txt file for swig-pypi to recognize when some form of flag/environment variable that when set disables the PCRE2 download/build, and instead calls find_package to locate the pcre2 library on the system to get the PCRE2_LIBRARY and PCRE2_INCLUDE_DIR paths to use.

can you make the patch? i can test the patch

**Comment by nightlark** [comment]
If you don't have any time constraint for when it is needed, I can make the patch.

**Comment by esaaprillia** [comment]
> If you don't have any time constraint for when it is needed, I can make the patch.

thank you. i will wait for that fix
