### ISSUE TITLE
Use setuptools_scm for versions

### ISSUE THREAD

**Issue by nightlark** [nightlark/swig-pypi#21]
[setuptools_scm](https://github.com/pypa/setuptools_scm) seems to be similar to versioneer but under the PyPA organization.

Switching from versioneer to PyPA would probably involve:
- Removing the automated publishing of versions to Test PyPI
- Removing versioneer related files
- Adding setuptools_scm to the pyproject.toml file with any needed settings, including using `write_to` for outputting a `_version.py` file

**Comment by rbSparky** [comment]
I would like to work on this, could you assign it to me?

**Comment by rbSparky** [comment]
Hello @nightlark, 
I am a bit stuck. When I run ```pipx run build --sdist``` I get ```build not found in package build. Available binaries: pyproject-build```. I'll try to get it to work, but I wanted to know if you knew how to fix this.

**Comment by nightlark** [comment]
Hey @rbSparky, I just got a chance to check -- not entirely sure why `pipx run build --sdist` isn't working, since that's what the CI builds use, though this alternative works on my machine:
```shell
pipx install build
pyproject-build --sdist
```

**Comment by nightlark** [comment]
Hi @rbSparky, I know you started some work on this -- did you want to keep working on it?

**Comment by rbSparky** [comment]
Hi @nightlark, sorry for the long silence, I had been working on the issue and tried to get it running on both windows and a linux distribution(debian) both of which didn't seem to work. So I didn't really know how to proceed.
But I tried to get it working again today and it somehow just worked(on debian). This is the output that I got ```Successfully built swig-4.1.0a2.dev17+g6f957b8.tar.gz```. 
Could you tell what is to be done now?

**Comment by nightlark** [comment]
Based on the file name, it seems like it could be working. I think next step is opening a PR to try building wheels for all supported platforms and see if their version info looks okay.
