### ISSUE TITLE
update to 4.1.0

### ISSUE THREAD

**Issue by jschueller** [nightlark/swig-pypi#62]
seems scripts need to be updated for pcre2 instead of pcre

**Comment by nightlark** [comment]
Thanks for the notification that version 4.1.0 was released. I have a change that should enable building SWIG 4.1.0 with PCRE2; I'm going to make sure the CI tests still pass with an older (non-CMake) SWIG version, then bump the version to 4.1.0 and make sure the various wheel artifacts look okay and work prior to pushing them to PyPI.

**Comment by nightlark** [comment]
Wheels have been uploaded to PyPI for swig 4.1.0 -- let me know if you run into any issues, it seems like there have been quite a few changes.

**Comment by jschueller** [comment]
thanks!
